### ISSUE TITLE
Update to GameStage 2.0 required

### ISSUE THREAD

**Issue by Xaikii** [OscarXcore/Tiered-Tooltips#1]
https://pastebin.com/gNV8cnk0

**Comment by Stapleton** [comment]
Sorry about that. Been on my todo list to get it updated but have been really busy. I will try to get something pushed out today!

On May 2, 2018 11:33 AM, Xaikii <notifications@github.com> wrote:

https://pastebin.com/gNV8cnk0

**Comment by Xaikii** [comment]
hehe ^^ np, I am only informing you about this :D

**Comment by Stapleton** [comment]
Thanks!
